name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: false
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run tests
        run: npm run test:coverage
        
      - name: Build package
        run: npm run build

  publish:
    needs: test
    runs-on: ubuntu-latest
    environment: 
      name: npm-publish
      url: https://www.npmjs.com/package/cryptonium
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch full history for proper versioning
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build package
        run: npm run build
        
      - name: Update package.json with correct repository info
        run: |
          npm pkg set repository.url="https://github.com/amantiwari57/cryptonium.git"
          npm pkg set bugs.url="https://github.com/amantiwari57/cryptonium/issues"
          npm pkg set homepage="https://github.com/amantiwari57/cryptonium#readme"
          npm pkg set author="Aman Tiwari <amantiwari57@example.com>"
        
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
        
      # Only run version bump if triggered manually
      - name: Bump version
        if: github.event_name == 'workflow_dispatch'
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          
      - name: Get current version
        if: github.event_name == 'release'
        run: |
          echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
        
      - name: Check if version exists on npm
        run: |
          if npm view cryptonium@${{ env.NEW_VERSION }} version 2>/dev/null; then
            echo "Version ${{ env.NEW_VERSION }} already exists on npm"
            exit 1
          else
            echo "Version ${{ env.NEW_VERSION }} is new, proceeding with publish"
          fi
        
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create Git tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          git tag v${{ env.NEW_VERSION }}
          git push origin v${{ env.NEW_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs: publish
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Notify success
        if: needs.publish.result == 'success'
        run: |
          echo "✅ Successfully published cryptonium to npm!"
          echo "📦 Package: https://www.npmjs.com/package/cryptonium"
          
      - name: Notify failure
        if: needs.publish.result == 'failure'
        run: |
          echo "❌ Failed to publish cryptonium to npm"
          echo "Please check the logs above for details"
